from __future__ import annotations

from typing import List, Literal

from pydantic import BaseModel, Field, HttpUrl


class SearchDecision(BaseModel):
    """
    Output of the reasoning/decision layer.
    Determines whether external search is required.
    """

    need_search: bool = Field(
        ...,
        description="Indicates whether an external web search is needed."
    )

    reason: str = Field(
        ...,
        min_length=5,
        description="Explanation for the search decision."
    )


class SearchResult(BaseModel):
    """
    Raw result returned from Tavily.
    """

    title: str = Field(
        ...,
        min_length=1,
        description="Title of the search result."
    )

    url: str

    snippet: str = Field(
        ...,
        min_length=1,
        description="Relevant snippet returned by search."
    )


class Source(BaseModel):
    """
    Source shown to the end user.
    """

    title: str = Field(
        ...,
        min_length=1,
        description="Source title."
    )

    url: str


class ResearchResponse(BaseModel):
    """
    Main educational response generated by the agent.
    """

    query_type: Literal["search", "no_search"]

    summary: str = Field(
        ...,
        min_length=10,
        description="High-level summary answering the user's query."
    )

    key_findings: List[str] = Field(
        default_factory=list,
        description="Important findings extracted from reasoning/search."
    )

    recommended_next_steps: List[str] = Field(
        default_factory=list,
        description="Suggested follow-up concepts or learning topics."
    )

    sources: List[Source] = Field(
        default_factory=list,
        description="Sources used to generate the response."
    )


class ReflectionReview(BaseModel):
    """
    Output of the reflection/self-evaluation stage.
    """

    is_complete: bool

    has_sources_when_needed: bool

    is_educational: bool

    should_revise: bool

    revision_notes: List[str] = Field(
        default_factory=list,
        description="Issues identified during reflection."
    )


class AgentRunOutput(BaseModel):
    """
    Full trace of a single agent execution.
    Useful for debugging, evaluation, and demonstrations.
    """

    user_query: str

    decision: SearchDecision

    tool_used: Literal["tavily", "none"] = "none"

    search_results: List[SearchResult] = Field(
        default_factory=list
    )

    response: ResearchResponse

    reflection: ReflectionReview